# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CanaryiOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
  # Pods for CanaryiOS

source 'https://github.com/CocoaPods/Specs.git'
pod 'FileBrowser', '~> 1.0'

end
